Repository bts-lasalle-avignon-projets/plug-in-pool-2025, pull requests merged in 2025-06, with the labels that each got.

#51 50 améliorer historique
  plug-in-pool-mobile/app/src/main/java/com/example/plug_in_pool/ActiviteConfigurationMatch.java
  plug-in-pool-mobile/app/src/main/java/com/example/plug_in_pool/ActiviteGestionPartie.java
  plug-in-pool-mobile/app/src/main/java/com/example/plug_in_pool/ActiviteHistorique.java
  plug-in-pool-mobile/app/src/main/java/com/example/plug_in_pool/ActivitePartie.java
  plug-in-pool-mobile/app/src/main/java/com/example/plug_in_pool/BaseDeDonnees.java
Labels: task

#53 52 corriger bug état du bluetooth
  README.md
  plug-in-pool-mobile/app/src/main/java/com/example/plug_in_pool/ActiviteGestionPartie.java
  plug-in-pool-mobile/app/src/main/java/com/example/plug_in_pool/ActivitePartie.java
Labels: bug

#61 58 afficher les statistiques à la fin dune partie
  plug-in-pool-visualisation/ecranfin.cpp
  plug-in-pool-visualisation/ecranfin.h
  plug-in-pool-visualisation/ecranmatch.h
  plug-in-pool-visualisation/ecranpartie.cpp
  plug-in-pool-visualisation/ecranpartie.h
  plug-in-pool-visualisation/ecranpluginpool.cpp
  plug-in-pool-visualisation/joueur.cpp
  plug-in-pool-visualisation/joueur.h
  plug-in-pool-visualisation/match.cpp
  plug-in-pool-visualisation/match.h
  plug-in-pool-visualisation/pluginpool.cpp
  plug-in-pool-visualisation/pluginpool.css
  plug-in-pool-visualisation/pluginpool.h
Labels: feature
